### ISSUE TITLE
problem with download vevo video

### ISSUE THREAD

**Issue by cuongtv51** [djiang9001/client_side_youtube_downloader#1] opened 2020-07-28 04:11 UTC
https://www.youtube.com/watch?v=Zlot0i3Zykw
I try this video but it not work, pls help me fix, thanks you so much.

**Comment by djiang9001** [comment] 2020-08-29 02:27
I just tried it and it worked, so the issue is fixed as of today. From time to time, Youtube will change something that will break the downloader, and I won't always be able to catch it instantly.

**Closed as completed by djiang9001** 2020-08-29 02:27 UTC
